// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjrnxghawrnradpsqead.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqcm54Z2hhd3JucmFkcHNxZWFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MDE0MTIsImV4cCI6MjA1MjQ3NzQxMn0.Zt5Ll3qAxsv9p-qBG3NpFRat8OYd-eUOw2mFd1SOZGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);